### ISSUE TITLE
Slider initialValue or value do not set initial position of slider handle

### ISSUE THREAD

**Issue by aaptho** [ReactUnity/material#2]
Using the **ReactUnity/full-sample** project, if I set `initialValue` or `value` for the Slider in `pages/material/index.tsx:127`, the slider handle still starts all the way to the left.

`<Slider initialValue={40} allowScroll direction="horizontal" mode="normal" max={100} step={20}>{(val) => val * val}</Slider>`

The same issue also happens in my own project when using this component.

**Comment by gkurt** [comment]
I noticed there were more issues with Slider. They should be fixed and working more like the web standards now. It will act like React controlled components when `value` exists, and uncontrolled otherwise. (https://reactjs.org/docs/forms.html#controlled-components)

Breaking change: Renamed `initialValue` to `defaultValue`.

Available in 0.9.2

**Comment by aaptho** [comment]
Tested and confirmed fixed in 0.9.2!
